### ISSUE TITLE
MVP's

### ISSUE THREAD

**Issue by simcha-c** [joedspin/bandramp#1]
Hey Joe :)

I took a look at your MVP's and here are a few things you should change.

1. The formatting of the list (like how it looks) is important for employers. It makes it more readable. So maybe make the titles for each MVP bold and a bit bigger.
2. Right now, each MVP is taking on too much. For example, the Albums MVP is taking on creating an albums page, uploading new albums, having the player work, buying/selling albums, etc. That is way too much for one MVP. [Here](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) are the suggested MVP's for fullstack projects and you can find the bandcamp ones on the page too.

All the MVP points should be what you would need to do in order to complete this specific MVP. Also, keep in mind that the 7 MVP's won't include every feature on the website. The 7 MVP's will be the basic features of what makes the site/app. After you finished all 7 of those, then you can definitely work on the cool features that you want to add.

Please let me know if you have any questions!

Best,
Simcha

**Comment by joedspin** [comment]
Hi Simcha,

The schema and mvp list have been updated to reflect the changes you and I discussed. Let me know how they look to you now.

Best,

Joe

**Comment by simcha-c** [comment]
**Albums**
- [x] Remember that we aren't going to be uploading the tracks to an album. Just the album info for this mvp. 

**Song Player**
- [x] Remember that for this part, we'll have to be able to know how to upload and save songs through the console.

**Upload / Download Songs**
- [x] we'll also have to create the track components. So uploading the track, adding info about the track etc. that should be another point in this mvp.
- [x] I would say that genre is going to be part of the carousel bonus. I don't think that it's a bonus you won't be able to get to, but it is it's own mvp.

**Search/Discover Section**
- [x] Since genre is going to be part of the bonus feature, the discover could be filtering options. Like, give me all albums that were released during this time. Things like that. 
- [x] Search field should also be able to search song titles. In the future, it should also be able to search by artist, etc.

**Carousel**
- [x] Please add some points to this one. It would be easier to complete if you know what needs to happen. This should include adding multiple genres on albums and songs.

Really great job!
